apiVersion: cache.techwithhuz.com/v1alpha1
kind: Techwithhuz
metadata:
  labels:
    app.kubernetes.io/name: techwithhuz
    app.kubernetes.io/instance: techwithhuz-sample
    app.kubernetes.io/part-of: techwithuz-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: techwithuz-operator
  name: techwithhuz-sample
spec:
  # TODO(user): Add fields here
