# permissions for end users to edit techwithhuzs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: techwithhuz-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: techwithuz-operator
    app.kubernetes.io/part-of: techwithuz-operator
    app.kubernetes.io/managed-by: kustomize
  name: techwithhuz-editor-role
rules:
- apiGroups:
  - cache.techwithhuz.com
  resources:
  - techwithhuzs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.techwithhuz.com
  resources:
  - techwithhuzs/status
  verbs:
  - get
